BASE_URL = 'https://www.instagram.com/'
PROFILES = ['']
USERNAMES = ['testunit_20203', 'holamundotest']
PASSWORDS = ['hola mundo 2022', 'hola muudno 2023']
GENERAL_WAITING_TIME = 2
STORES_TIMEOUT = 5
NEXT_STORIES_BUTTON = 6
GENERAL_EXPLICIT_WAIT_TIME = 10
PAUSE_ANTI_BOT = 3
RESOURCES = '../resources'
STORES = 'stores'
POSTS = 'posts'
REELS = 'reels'
TAGGED = 'tagged'
DIV_STORES = 'div._aarf._aarg'
DIV_NAME_STORE = 'a.x1i10hfl.xjbqb8w.x6umtig.x1b1mbwd.xaqea5y.xav7gou.x9f619.x1ypdohk.xt0psk2.xe8uvvx.xdj266r.x11i5rnm.xat24cr.x1mh8g0r.xexx8yu.x4uap5.x18d9i69.xkhd6sd.x16tdsg8.x1hl2dhg.xggy1nq.x1a2a7pz.notranslate._ac0s._a6hd'
HOST = "localhost"
DB = "dataharvest"
USER = "admin"
PASSWORD = "dataharvest"
